application: hexapicserv
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  mime_type: text/html
  static_files: static/index.html
  upload: static/index.html
- url: /quiz
  mime_type: text/html
  static_files: static/quiz/index.html
  upload: static/quiz/index.html
- url: /quiz
  static_dir: static/quiz

- url: /.*
  script: _go_app